name: flutter_aws_s3service
description: "flutter_aws_s3service plugin allows users to upload 、download 、list、 delete image for amazon s3"
version: 0.0.1
homepage: https://github.com/larackg/flutter_aws_s3service

environment:
  sdk: ">=3.5.4 <4.0.0"
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
#  plugin_platform_interface: ^2.0.2
#  path: ^1.8.0
#  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
#  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.larack.s3service.flutter_aws_s3service
        pluginClass: FlutterAwsS3servicePlugin
      ios:
        pluginClass: FlutterAwsS3servicePlugin
